project_name: "Customer Churn"
author: "Harinder Singh Sudwal"

base:
  test_size: 0.2


folder_path: 
  artifacts: "artifacts"
  raw_path: "raw"
  train: "train.csv"
  test: "test.csv"

# data_validate:
  validate_path: "validate"
  train_val: "vali_train.csv"
  test_val: "vali_test.csv"

# data_transformer:
  transform_path: "transformer"
  transformer: "transformer.pkl"
  xtrain: "xtrain.csv"
  xtest: "xtest.csv"
  ytrain: "ytrain.csv"
  ytest: "ytest.csv"

# model:
  model_path: "model"
  saved_model: "best_model.pkl"